# Day 1 — Core Mechanics

**Source (strict):** Kaggle Pandas micro-course: https://www.kaggle.com/learn/pandas

**Dataset:** winemag-data-130k-v2.csv

Attempt each question in its own code cell below. Add a short markdown note with your answer/finding after each.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# df = pd.read_csv('your_dataset.csv')  # <-- point this at your downloaded dataset

### Q1. Load the wine reviews CSV. Print shape, dtypes, and first 5 rows.

In [6]:

wine_reviews = pd.read_csv(r"C:\Users\shata\Downloads\winemag-data-130k-v2.csv.zip", index_col=0)
wine_reviews.shape
wine_reviews.dtypes
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Q2. Select the `country` and `points` columns only, first 15 rows.

In [6]:
wine_reviews.loc[:14, ['country', 'points']]

     country  points
0      Italy      87
1   Portugal      87
2         US      87
3         US      87
4         US      87
5      Spain      87
6      Italy      87
7     France      87
8    Germany      87
9     France      87
10        US      87
11    France      87
12        US      87
13     Italy      87
14        US      87

### Q3. Select all rows where `points >= 95` AND `price <= 20`.

In [7]:
wine_reviews.loc[(wine_reviews.points>=95) & (wine_reviews.price<=20)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
5011,US,"Truly stunning, the Lewis Estate Riesling from...",Lewis Estate Vineyard,95,20.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Dunham 2010 Lewis Estate Vineyard Riesling (Co...,Riesling,Dunham
15196,France,"The home vineyard of Madiran's star, Alain Bru...",Château Bouscassé,95,20.0,Southwest France,Madiran,NaN,Roger Voss,@vossroger,Alain Brumont 2010 Château Bouscassé Red (Madi...,Red Blend,Alain Brumont
76570,US,Spectacular is the word that comes to mind her...,Bacchus Vineyard,95,20.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Januik 2012 Bacchus Vineyard Riesling (Columbi...,Riesling,Januik
101580,US,"Superb fruit highlights this tight, sculpted S...",NaN,96,20.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Rulo 2007 Syrah (Columbia Valley (WA)),Syrah,Rulo
126242,US,"With residual sugar at about 1.35%, this balan...",NaN,95,20.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Poet's Leap 2009 Riesling (Columbia Valley (WA)),Riesling,Poet's Leap

### Q4. Select all rows where `country` is either 'Italy' or 'France'.

In [8]:
wine_reviews.loc[(wine_reviews.country == 'Italy') | (wine_reviews.country == 'France')]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### Q5. Get the row with the highest `points` value using `.idxmax()`.

In [7]:
best_wine = wine_reviews.loc[wine_reviews.points.idxmax()]

### Q6. Count how many reviews have a null `price`.

In [8]:
wine_reviews.price.isnull().sum()

8996

### Q7. Find the mean `points` and the median `price`.

In [7]:
wine_median=wine_reviews.points.median()
wine_mean=wine_reviews.points.mean()
print(wine_median , wine_mean)

88.0 88.44713820775404

### Q8. Get unique values in `country` and count them.

In [5]:
wine_reviews.country.value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

### Q9. Rename `points` to `rating` and `price` to `cost`.

In [15]:
wine_reviews.rename(columns={'points': 'rating' , 'price': 'cost'})

,country,description,designation,rating,cost,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### Q10. Sort the DataFrame by `cost` descending, then `rating` descending.

In [18]:
wine_reviews.sort_values(by=['price' , 'points' ], ascending=[False, False])

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
80290,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Château les Ormes Sorbet 2013 Médoc,Bordeaux-style Red Blend,Château les Ormes Sorbet
15840,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2014 Pomerol,Bordeaux-style Red Blend,Château Pétrus
98380,France,"A superb wine from a great year, this is power...",NaN,96,2500.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Domaine du Comte Liger-Belair 2010 La Romanée,Pinot Noir,Domaine du Comte Liger-Belair
120391,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,Chardonnay,Blair
65352,France,This extravagantly perfumed wine has great jui...,NaN,97,2000.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2011 Pomerol,Bordeaux-style Red Blend,Château Pétrus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107767,Italy,"A boxed wine, this blend of Pinot Noir and Mer...",Pinot Noir-Merlot,81,NaN,Veneto,Venezia,NaN,NaN,NaN,Duca del Frassino 2010 Pinot Noir-Merlot Red (...,Red Blend,Duca del Frassino
121877,France,"This is a yeasty wine, with the fruit less evi...",NaN,81,NaN,Burgundy,Bourgogne,NaN,Roger Voss,@vossroger,Domaine Luquet 2010 Bourgogne,Chardonnay,Domaine Luquet
123461,Italy,There aren't that many organic Proseccos out t...,Brut,81,NaN,Veneto,Prosecco,NaN,NaN,NaN,La Jara NV Brut (Prosecco),Glera,La Jara
117025,Portugal,A curious sauerkraut perfume leads to a hard e...,NaN,80,NaN,Lisboa,NaN,NaN,Roger Voss,@vossroger,Quinta do Pinto 2008 Touriga Nacional (Lisboa),Touriga Nacional,Quinta do Pinto
123541,Italy,"This Valpolicella blend opens with an aged, br...",Corte Antica,80,NaN,Veneto,Valpolicella Classico Superiore,NaN,NaN,NaN,Cantine Benedetti 2008 Corte Antica (Valpolic...,"Corvina, Rondinella, Molinara",Cantine Benedetti